[workspace]
members = [
    "crates/piet-glow",
    "crates/piet-hardware",
    "crates/piet-wgpu",
    "run-wasm"
]

resolver = "2"

[patch.crates-io]
piet-cosmic-text = { git = "https://github.com/notgull/piet-cosmic-text" }
